# Generated by Django 4.2.3 on 2024-06-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleText', models.CharField(max_length=50)),
                ('aboutme', models.TextField(max_length=2000)),
                ('counterOneName', models.CharField(max_length=30)),
                ('counterOneNumber', models.IntegerField(default=0)),
                ('counterTwoName', models.CharField(max_length=30)),
                ('counterTwoNumber', models.IntegerField(default=0)),
                ('counterThreeName', models.CharField(max_length=30)),
                ('counterThreeNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#', max_length=7)),
                ('Logolink', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('sort_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('sort_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mainImage', models.CharField(default="{% static 'allawi.png'%}", max_length=1500)),
                ('smallContent', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('instaAcc', models.CharField(max_length=1000)),
                ('whatsNumber', models.CharField(max_length=1000)),
                ('linkedinAcc', models.CharField(max_length=1000)),
                ('facebookAcc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=1500)),
                ('photoTitle', models.CharField(blank=True, default='Photo', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(db_index=True, default='Imagination Trumps Knowledge!', max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('fullWidth', models.BooleanField(default=False)),
                ('mainPhoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aliPortfolio.photos')),
                ('photos', models.ManyToManyField(blank=True, to='aliPortfolio.photos')),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(db_index=True, default='Words Can Change The World!', max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=500)),
                ('smallDetails', models.CharField(max_length=50)),
                ('mainPhoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainPhoto', to='aliPortfolio.photos')),
            ],
        ),
    ]
