# Generated by Django 5.1 on 2025-01-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TitleText', models.CharField(max_length=50)),
                ('personalImage', models.CharField(default='https://lh3.googleusercontent.com/drive-viewer/AKGpihZywZtaaSEZ4A1rQqLZH_MBMnKemFTDwvQcNLtgdFcv2M5zkxAGqFTQPh7hJwq11Q-C-toJHtupsV2792rGTs60MIA86rySKA=s1600-rw-v1', max_length=1500)),
                ('aboutme', models.TextField(max_length=2000)),
                ('counterOneName', models.CharField(max_length=30)),
                ('counterOneNumber', models.IntegerField(default=0)),
                ('counterTwoName', models.CharField(max_length=30)),
                ('counterTwoNumber', models.IntegerField(default=0)),
                ('counterThreeName', models.CharField(max_length=30)),
                ('counterThreeNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logolink', models.TextField(max_length=2500)),
                ('MainLogo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('sort_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=2000)),
                ('sort_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('personalImage', models.CharField(default='https://lh3.googleusercontent.com/drive-viewer/AKGpihYOZsaMEyC0OCUZK9MDbH-6pS0L4bbc8JIFVAGVdUCl-wu275ocp6fEPSW3gJU5Seecl_NPwcNSyZttQ8seijhTtVeU39jcNw=s1600-rw-v1', max_length=1500)),
                ('smallContent', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
                ('instaAcc', models.CharField(max_length=1000)),
                ('whatsNumber', models.CharField(max_length=1000)),
                ('linkedinAcc', models.CharField(max_length=1000)),
                ('facebookAcc', models.CharField(max_length=1000)),
                ('logo', models.CharField(default='Nothing', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=1500)),
                ('photoTitle', models.CharField(blank=True, default='Photo', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gallerys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(db_index=True, default='Imagination Trumps Knowledge!', max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('visitLink', models.TextField(default='1', max_length=2500)),
                ('photo', models.TextField(default='1', max_length=2500)),
                ('fullWidth', models.BooleanField(default=False)),
                ('mainPhoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='aliPortfolio.photos')),
            ],
        ),
    ]
