# Generated by Django 4.2.3 on 2024-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='mainImage',
            new_name='personalImage',
        ),
        migrations.AddField(
            model_name='abouts',
            name='personalImage',
            field=models.CharField(default="{% static 'allawi.png'%}", max_length=1500),
        ),
    ]
