# Generated by Django 5.1 on 2025-01-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerys',
            name='mainPhoto',
        ),
    ]
