# Generated by Django 4.2.3 on 2024-06-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0002_rename_mainimage_home_personalimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
