# Generated by Django 5.1 on 2025-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0002_remove_gallerys_mainphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AlterField(
            model_name='gallerys',
            name='photo',
            field=models.TextField(default='https://i.imgur.com/DzlrvEa.jpeg', max_length=2500),
        ),
    ]
