# Generated by Django 4.2.3 on 2024-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0003_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='MainLogo',
            field=models.BooleanField(default=False),
        ),
    ]
