# Generated by Django 5.1 on 2025-02-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0003_delete_photos_alter_gallerys_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='bts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoLink', models.TextField(max_length=2500)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=100)),
            ],
        ),
    ]
