# Generated by Django 5.1 on 2025-02-20 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0004_bts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
