# Generated by Django 4.2.3 on 2024-06-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0004_clients_mainlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='color',
        ),
    ]
