# Generated by Django 5.1 on 2025-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliPortfolio', '0005_bts_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='bts',
            name='title',
        ),
        migrations.AddField(
            model_name='bts',
            name='header',
            field=models.TextField(default='Behind The Scenes', max_length=200),
        ),
    ]
